services:

  django:
    container_name: django
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  vue-app:
    container_name: vue-app
    command: nodemon --ext js,css,vue --watch src --exec npm run serve
    build:
      context:  front
      dockerfile: Dockerfile
    volumes:
      - './front:/app'
      - '/app/node_modules'

    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    environment:
    # Chokidar, which Webpack uses for watching changes has an environment to force the use of polling: CHOKIDAR_USEPOLLING
    - CHOKIDAR_USEPOLLING=true
    - HOST=0.0.0.0

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue-app
      - django
